### ISSUE TITLE
Quicklook do not follow file selection

### ISSUE THREAD

**Issue by daslicht** [WilliamDrt/DrtFMngPreview#7]
Hi,
when I audition a file with space and then move to the next, quicklook will not play it.

How to make the fonts bigger in Direttore ?

**Comment by WilliamDrt** [comment]
This is by design. You'll have to hit spacebar again if you want to preview another file. 
The idea was to have a preview one file for reference, while opening another file for editing.
I know that QL has a pin button, but users over here thought that this design is better
There will be a user option to change this behavior, in a feature version

Text size:
Menu (the first button)
Text
Larger/smaller/reset

or Ctr +/-/0

**Comment by daslicht** [comment]
ok thank you
